# Generated by Django 5.1.4 on 2025-02-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
