# Generated by Django 4.2.1 on 2023-07-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_person_rename_context_post_content_remove_post_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='person',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
