# Generated by Django 5.1.4 on 2025-01-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-journal_date'],
            },
        ),
    ]
