# Generated by Django 4.2.1 on 2023-07-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Journaling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='mood_score',
        ),
    ]
