# Generated by Django 4.2.1 on 2023-07-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journaling', '0002_remove_journal_mood_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-title']},
        ),
        migrations.AddField(
            model_name='journal',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
