# Generated by Django 4.2.1 on 2023-07-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Journaling', '0003_alter_journal_options_journal_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-journal_date']},
        ),
    ]
