# Generated by Django 4.2.1 on 2023-08-05 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyMood', '0006_alter_datamood_options'),
        ('Journaling', '0008_alter_journal_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='mood',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyMood.datamood'),
        ),
    ]
