# Generated by Django 4.2.1 on 2023-08-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Journaling', '0009_journal_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='mood',
        ),
    ]
