# Generated by Django 3.2.20 on 2024-09-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journaling', '0010_remove_journal_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
