# Generated by Django 4.2.1 on 2023-07-21 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Endeavors', '0010_alter_endeavor_program_title_alter_task_task_title'),
        ('To_Do', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200, null=True, unique=True)),
                ('set_time', models.TimeField(null=True)),
                ('is_done', models.BooleanField(blank=True, default=False, null=True)),
                ('endeavor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_tasks', to='Endeavors.endeavor')),
            ],
        ),
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
