# Generated by Django 4.2.1 on 2023-07-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do', '0004_alter_task_is_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_done',
            new_name='completed',
        ),
    ]
