# Generated by Django 4.2.1 on 2023-08-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do', '0007_rename_endeavor_task_goal_alter_task_starting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
