# Generated by Django 4.2.1 on 2023-07-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataVisualization', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoodData',
        ),
        migrations.DeleteModel(
            name='WorkData',
        ),
    ]
