# Generated by Django 4.2.1 on 2023-08-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataVisualization', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousmonth',
            name='average',
            field=models.FloatField(),
        ),
    ]
