# Generated by Django 4.2.1 on 2023-08-10 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DataVisualization', '0004_alter_previousmonth_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousmonth',
            name='user',
            field=models.ForeignKey(default='slim', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
