# Generated by Django 4.2.1 on 2023-08-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataVisualization', '0005_previousmonth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousmonth',
            name='average',
            field=models.CharField(max_length=100),
        ),
    ]
