# Generated by Django 4.2.1 on 2023-08-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataVisualization', '0006_alter_previousmonth_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousmonth',
            name='average',
            field=models.FloatField(),
        ),
    ]
