# Generated by Django 4.2.1 on 2023-08-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataVisualization', '0008_remove_previousmonth_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreviousMonth',
        ),
    ]
