# Generated by Django 4.2.1 on 2023-06-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=30)),
                ('mood_score', models.IntegerField()),
                ('mood_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
