# Generated by Django 4.2.1 on 2023-08-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamood',
            name='mood',
        ),
        migrations.AlterField(
            model_name='datamood',
            name='mood_score',
            field=models.CharField(choices=[('1', 'Happy'), ('2', 'Soso'), ('3', 'upset'), ('4', 'nervous'), ('5', 'stressed')], max_length=1),
        ),
    ]
