# Generated by Django 4.2.1 on 2023-08-02 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyMood', '0002_remove_datamood_mood_alter_datamood_mood_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamood',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datamood',
            name='mood_score',
            field=models.CharField(choices=[('1', 'Happy'), ('2', 'Soso'), ('3', 'upset'), ('4', 'nervous'), ('5', 'stressed')], default='1', max_length=1),
        ),
    ]
