# Generated by Django 4.2.1 on 2023-08-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMood', '0006_alter_datamood_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamood',
            name='mood_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
