# Generated by Django 4.2.1 on 2023-08-09 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyMood', '0007_alter_datamood_mood_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datamood',
            options={'ordering': ['-id']},
        ),
    ]
