# Generated by Django 4.2.1 on 2023-08-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMood', '0009_alter_datamood_mood_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamood',
            name='mood_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
