# Generated by Django 3.2.20 on 2023-09-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMood', '0010_alter_datamood_mood_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamood',
            name='mood_score',
            field=models.IntegerField(),
        ),
    ]
