# Generated by Django 3.2.20 on 2023-09-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMood', '0011_alter_datamood_mood_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamood',
            name='mood_date',
            field=models.DateField(),
        ),
    ]
