# Generated by Django 3.2.20 on 2023-09-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMood', '0012_alter_datamood_mood_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamood',
            name='mood_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
