# Generated by Django 4.2.1 on 2023-07-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Endeavors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('set_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='endeavor',
            name='Content',
        ),
        migrations.RemoveField(
            model_name='endeavor',
            name='endeavor_date',
            field=models.DateTimeField(null=False),
        ),
        migrations.AddField(
            model_name='endeavor',
            name='duration',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='endeavor',
            name='start_day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='endeavor',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
