# Generated by Django 4.2.1 on 2023-07-09 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Endeavors', '0002_task_remove_endeavor_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='endeavor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Endeavors.endeavor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='set_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
