# Generated by Django 4.2.1 on 2023-07-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Endeavors', '0003_task_endeavor_alter_task_set_date_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endeavor',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
