# Generated by Django 4.2.1 on 2023-07-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Endeavors', '0004_alter_endeavor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endeavor',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
