# Generated by Django 4.2.1 on 2023-07-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Endeavors', '0005_task_description_task_is_done_alter_endeavor_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
    ]
