# Generated by Django 4.2.1 on 2023-07-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Endeavors', '0006_alter_task_is_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endeavor',
            old_name='title',
            new_name='program_title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task_title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='set_date',
        ),
        migrations.AddField(
            model_name='task',
            name='set_time',
            field=models.TimeField(null=True),
        ),
    ]
