# Generated by Django 4.2.1 on 2023-07-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Endeavors', '0007_rename_title_endeavor_program_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
