# Generated by Django 4.2.1 on 2023-07-11 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Endeavors', '0008_alter_task_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='endeavor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Endeavors.endeavor'),
        ),
    ]
