# Generated by Django 4.2.1 on 2023-07-23 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Endeavors', '0010_alter_endeavor_program_title_alter_task_task_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endeavor',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='endeavor',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
