# Generated by Django 4.2.1 on 2023-08-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Endeavors', '0011_alter_endeavor_options_endeavor_author_delete_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endeavor',
            old_name='start_day',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='endeavor',
            old_name='program_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='endeavor',
            name='duration',
        ),
    ]
