# Generated by Django 4.2.1 on 2023-08-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Endeavors', '0012_rename_start_day_endeavor_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endeavor',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
