# Generated by Django 3.2.20 on 2023-09-08 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Endeavors', '0013_alter_endeavor_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endeavor',
            options={'ordering': ['id']},
        ),
    ]
