# Generated by Django 3.2.20 on 2023-09-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Endeavors', '0014_alter_endeavor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endeavor',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
