# Generated by Django 4.2.1 on 2023-08-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accomplished', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accomplishedgoal',
            options={'ordering': ['-id']},
        ),
    ]
